FROM ubuntu

WORKDIR /app

COPY . /app

RUN apt-get update
RUN apt-get install -y python3-pip
RUN pip install -y PIL
RUN pip install -r ./Deployment/Requirements.txt


CMD streamlit run ./Deployment/api.py